@startuml

package @ПУФ {
    :Web-разработчик:
    :Backend-разработчик:
}

package @HMI {
    :Тестировщик:
}

package @БеспилотныйАвтомобиль {
    :QA-водитель:
    :ML-разработчик:
    :DataEngineer:
}

:Web-разработчик: --> (Разработка интерфейса)
:Backend-разработчик: --> (Разработка API)
:Тестировщик: --> (Тестирование приложений)
:QA-водитель: --> (Тестирование работы автомобиля)
:ML-разработчик: --> (Создание алгоритма беспилотного управления)
:DataEngineer: --> (Формирование и обработка данных)

@enduml
