@startuml
left to right direction

frame КомандаПУФ {

    :Тех поддержка: as Support
    :Администратор: as Admin
    Admin <|-- Support
}

frame Тестирование {
    :Водитель:
    :Автомобиль: as Auto
}

frame ТехОтдел {
    :Ответственный за флот: as FleetManager
    :Главный инженер: as Engineer
    :Техник: as Technician
}

frame Разработчики {
    :ML-разработчик:
}

frame ПУФ {
    (Управление правами) as (RM)
    (Назначение прав) as (R)
    (Авторизация) as (Auth)

    (R) .> (Auth) : include
    (ServiceManagement) .> (Auth) : include
    (CarManagement) .> (Auth) : include

    Admin -down-> (RM)
    Support -down-> (R)
    (R) <|-- (RM)

    frame Бронирования {
        (Бронирование машин для проверки написанных алгоритмов) as (Reservation)
        (Отметка занятых машин и водителей) as (Calendaring)

        :ML-разработчик: --> (Reservation)
        (Reservation) -> (Calendaring)

        (Reservation) ..> (Auth) : include
    }

    frame Автопарк {
        (Создание расписания машин и водителей) as (CarManagement)
        (Управление автомобилем) as (Riding)
        (Назначение и создание задач\n на ремонт и поддержку автомобиля) as (ServiceManagement)
        (Изменение статуса текущей задачи,\n написание комментариев в ней) as (ServiceWork)
        (Ведение католога задач) as (Tasks)

        :Engineer: --> (ServiceManagement)
        (ServiceManagement) --> (Tasks)
        :Technician: --> (ServiceWork)
        (ServiceWork) -> (Tasks)
        (Tasks) -> (CarManagement)

        :FleetManager: --> (CarManagement)
        :Водитель: --> (Riding)
        (Riding) --- (Calendaring)
        :Auto: --> (Отправка данных тестирования на сервер)
        :Auto: --- (Riding)
        (CarManagement) --- (Calendaring)
    }

}

@enduml
