@startuml
left to right direction

package @КомандаПУФ {

    :Тех поддержка: as Support
    :Администратор: as Admin
    Admin <|-- Support
}

package @Тестирование {
    :QA-водитель:
    :водитель:
}

package @ТехОтдел {
    :Ответственный за флот:
    :Главный инженер:
    :Техник:
}

package @Разработчики {
    :ML-разработчик:
}

package @ПУФ {

    package @Доступы {
        (Управление правами) as (RM)
        (Назначение прав) as (R)
        (R) <|-- (RM)

        Admin --> (RM)
        Admin --> (Создание типов броней)
        Support --> (R)
    }

    package @Мастерская {
        :Ответственный за флот: --> (Распределение компонентов флота:\n автомобилей, ремонт-постов...)
        :Главный инженер: --> (Назначение и создание задач)
        :Техник: --> (Изменение статуса текущей задачи,\n написание комментариев в ней)
    }

    package @РазделБронирования {
        (Тестирование работы автомобиля,\n проверка работы интерфейса внутри машины) as (FullTesting)
        (FullTesting) <|-- (Занесение данных тестирования)

        :ML-разработчик: --> (Бронирование машин для проверки написанных алгоритмов)
        :QA-водитель: --> (FullTesting)
        :водитель: --> (Занесение данных тестирования)
    }

}

@enduml
